apiVersion: v1
kind: Pod
metadata:
  name: myapp-nginx
  labels:
    app: myapp
spec:
  containers:
  - name: myapp
    image: nginx:latest
    ports:
      - containerPort: 80

---

apiVersion: v1
kind: Pod
metadata:
  name: myapp-blue
  labels:
    app: myapp
spec:
  containers:
  - name: myapp
    image: achinta1/achinta-colors:blue
    ports:
      - containerPort: 80
